.\" Manpage for EpiMath100.
.\" Contact poulet_a@epitech.eu, bauwen_j@epitech.eu and broggi_t@epitech.eu in to correct errors or typos.
.TH man 1 " 2014" "1.7.0" "EpiMath100 man page"

.SH NAME
EpiMath100

.SH SYNOPSIS
EpiMath100 is a library in ruby which will help to create a Vector, a Matrix, ... There is few class avaliables :

.TP
\fBLine \fR
Line is a basic library to manipulate a line in 3 dimensions. It use vectors, equations etc. and can calculate a point of the line with a coeficient.

.TP
\fBMatrix \fR
Using and manipulating a Matrix easy.

.TP
\fBPoint \fR
Using and manipulating a Point in 3 dimensions.

.TP
\fBPolynomial \fR
This class allow you to manipulate polynomial function.
It can calculate the derived function.

.TP
\fBVector \fR
Using and manipulating a Vector in 3 dimensions.

.SH DESCRIPTION
EpiMath100

.SH OPTIONS
The EpiMath100 does not take any options.

.SH SEE ALSO
No related manpage.

.SH REPORTING BUGS
No known bugs.
.br
Report epimath100 bugs to arthur.poulet@epitech.eu, thibaut.broggi@epitech.eu, or jordan.bauwens@epitech.eu

.SH AUTHOR
poulet_a, broggi_t, bauwen_j, caudou_j
