.\" Manpage for ruby_sources.
.\" Contact poulet_a@epitech.eu and broggi_t@epitech.eu .in to correct errors or typos.
.TH man 1 " 2013" "1.0" "ruby_sources man page"
.SH NAME
ruby_sources \- create a new LDAP user
.SH SYNOPSIS
ruby_sources
.SH DESCRIPTION
ruby_sources
.SH OPTIONS
The ruby_sources does not take any options.
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
poulet_a, broggi_t
